### ISSUE TITLE
SSL error on chrome / disable SSL mode

### ISSUE THREAD

**Issue by ghost** [aliuosio/mage2.docker#8]
Hi,

Hope you are all well !

I wanted to deploy locally your repository and after executing
```bash
./install.sh
```

My browser (Chrome/MacOSX) displays:
```
Your connection is not private
Attackers might be trying to steal your information from mage2.local.com (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_INVALID
```

Ps. mage2.local.com was changed as letsencrypt triggered it could not validate the certificate as no valid TLD.

My questions:
- Can you describe more how to deploy it on MacOSX ?
- Can you tell me how to disable the SSL mode for now ?

Thanks in advance for your insights an inputs.

Cheers,
X

**Comment by aliuosio** [comment]
i am working on the letsencrpyt / nginx certificate generation right now.
the letsencrypt cert does not work under localhost generally.
You need a valid domain which can be reached from outside for that.

The Nginx Certificate has to be mapped to a folder in your home directory so you can then add it to the OSX Keychain. The One generated while the Nginx container is built with Dockerfile.
i am working on the mapping also right now.

i will keep you posted. 
Hope to get it done the next two days because the current state of the repo leads to a Nginx Container failing to start.

**Comment by aliuosio** [comment]
Use this tutorial for Port 80 Nginx Config:

https://firebearstudio.com/blog/magento-2-nginx-configuration.html

**Comment by ghost** [comment]
thanks for your replies because I am really eager to test your deploy :-)

btw. a non-ssl mode would be awesome still ^^

**Comment by aliuosio** [comment]
Feel free to work on some todos in the README. There still lots to be done.
We could get a good stack with pwa studio integration later on

**Comment by rakibabu** [comment]
Hi @aliuosio ,

Did you had a look on this script? https://github.com/Neilpang/acme.sh this auto generates letsencrpyt certificates and does everything what you want.

**Comment by aliuosio** [comment]
@rakibabu 
we have two problems hier.

1. The Cert generated locally by Nginx Dockerfile on docker-compose build
(this does not work with letsencrpyt container because you need a qualified domain)
should be mounted to a path on the host system so you can add it to the OSX Keychain which allows you to call https on localhost in your browser

2. The Cert Generation on server(not localhost) with real domain name works already but maybe your version works a little better :-)
Will try to exchange the letsencrypt containers with your Example when Problem 1 is fixed.

thx for your efforts  :-)

**Comment by ghost** [comment]
just for mentioning, they use traefik https://github.com/chellinki/alpine-magento2

**Comment by aliuosio** [comment]
@x0rzkov 
fixed... i will keep the issue open till you can give me feedback.
So please get back to me on this issue

**Comment by ghost** [comment]
```bash
Step 9/13 : COPY conf/zz-docker.conf /usr/local/etc/php-fpm.d/
 ---> a9ebc41734d9
Step 10/13 : COPY conf/xdebug.ini /usr/local/etc/php/conf.d/
 ---> 917a2a5bdf95
Step 11/13 : COPY conf/auth.json /home/$USER/.composer/
ERROR: Service 'php' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder785691527/conf/auth.json: no such file or directory
```

I  have the following error while building

**Comment by aliuosio** [comment]
> ```shell
> Step 9/13 : COPY conf/zz-docker.conf /usr/local/etc/php-fpm.d/
>  ---> a9ebc41734d9
> Step 10/13 : COPY conf/xdebug.ini /usr/local/etc/php/conf.d/
>  ---> 917a2a5bdf95
> Step 11/13 : COPY conf/auth.json /home/$USER/.composer/
> ERROR: Service 'php' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder785691527/conf/auth.json: no such file or directory
> ```
> 
> I have the following error while building

fixed

**Comment by ghost** [comment]
you need to add those lines somewhere in ./install.sh

```bash
docker volume create --name=app_data     
docker volume create --name=letsencrypt_certs
```

and i have no ssl dir as described in readme: "on OSX add the keys in .docker/nginx/ssl to your keychain to use https in browser"

**Comment by ghost** [comment]
```yaml
version: "2"

options:
  verbose: true

syncs:
  app_data:
    src: ${PWD}/htdocs
    sync_strategy: 'native_osx'
    sync_userid: 1000
    sync_groupid: 1000
    sync_args:
    - "-prefer newer"
    - "-ignore='Path .git'"
    - "-ignore='BelowPath .git'"

  letsencrypt_certs:
    src: ${PWD}/.docker/nginx/ssl
    sync_strategy: 'native_osx'
    sync_args:
      - "-prefer newer"
      - "-ignore='Path .git'"
      - "-ignore='BelowPath .git'"
```

missing ssl folder preventing docker-sync to work properly as missing brackets around $PWD -> ${PWD}

but still not working for me, I have a 404 page on https://mage2.local.com/admin (I modified the .env file for this domain)

**Comment by aliuosio** [comment]
@x0rzkov
docker-sync start; 
did you do this before starting the containers or the install.sh on OSX?
added the command to the README.md

**Comment by ghost** [comment]
after ./install.sh, I started docker sync start, then keys appeared and the privkey.pem was rejected by keychain access

**Comment by aliuosio** [comment]
i am on it. maybe you can find a solution with me. chapeau

**Comment by aliuosio** [comment]
will look it up first thing in the morning.

**Comment by ghost** [comment]
ok it works but some headaches....

- It is **really slow to run composer** on my Macbook Air while fetching/adding the 950 modules.
- It works only on **safari** if the 'fullchain.pem' is added to keychain access
- It is globally really l**ong and slow to display pages** from admin or front (>60seconds)
- Would be awesome to run a command **to disable the ssl for dev** purpose

**Comment by aliuosio** [comment]
> ok it works but some headaches....
> 
> * It is **really slow to run composer** on my Macbook Air while fetching/adding the 950 modules.
i hop you are using docker sync. Ye, it takes time because magento 2 uses looks of Resources to install-
> * It works only on **safari** if the 'fullchain.pem' is added to keychain acces
ok
> * It is globally really l**ong and slow to display pages** from admin or front (>60seconds)
standard at the beginning when it loads everything into the cache. 

> * Would be awesome to run a command **to disable the ssl for dev** purpose
yeah, we could add a prompt to the install.sh to choose between or on mac it always uses the non-SSL version. The last Option would be the fastest to build because we would still have the problem of mapping the ssl folder if you choose SSL on the mac
It is headache on linux already so on  mac the loading time becomes a pain in the ass.
you are free to make a fork for this. i will turn of the directory mapping on the ssl folder to the host system for now.

**Comment by aliuosio** [comment]
SSL does not make the App much slower if you use Dockstation to look at the containers perfomance you will notice that the PHP container uses most of the cpu and ist over 100% on first install or run

**Comment by ghost** [comment]
For the SSL, I wanted to test also https://github.com/cmehay/docker-tor-hidden-service with the port 80

**Comment by aliuosio** [comment]
the hidden service would be on the net. so a valid cert can be done with letsencrypt nad servers dont run on mac. Is it only available on 80.
so a prompt would be the best to choose between ssl and non-ssl.
but the prompt of install.sh would only show up on non mac systems when running it on localhost.
this would be the best solution for the mac problen and your hidden service that seems to only run on 80

**Comment by aliuosio** [comment]
feel free to fork the project and make the solution

**Comment by ghost** [comment]
I need to find a way to disable SSL after install 

ref.
- https://stackoverflow.com/questions/23167400/how-to-remove-https-from-admin-panel-in-magento-database-as-getting-403-error
- https://magento.stackexchange.com/questions/30985/how-to-disable-forced-redirects-in-magento 

PS. I made the solution for prestashop https://github.com/x0rzkov/docker-prestashop1.7.x-php7-fpm-tor-hidden

**Comment by ghost** [comment]
I tried the following but does not work for disabling ssl from ./install.sh :-(

```bash
magentoInsecure() {
    docker exec -it -u $1 $2 bin/magento setup:store-config:set --use-secure=0 --base-url="http://$3"
    docker exec -it -u $1 $2 bin/magento setup:store-config:set --use-secure-admin=0 --base-url="http://$3"
    docker exec -it -u $1 $2 bin/magento cache:flush
}

. ${PWD}/.env;

magentoInsecure \
    ${USER} \
    ${NAMESPACE}_php \
    ${SHOP_URI}
```

**Comment by ghost** [comment]
I found that https://github.com/FiloSottile/mkcert, a simple zero-config tool to make locally trusted development certificates with any names you'd like. Maybe it could help for local domains and ssl.

Found an implementation with docker-compose, the nginx dir, with https://foo.test works for me
https://github.com/HugoDF/docker-compose-local-https
